services:

  scylla:
    container_name: scylla
    image: scylladb/scylla:6.2.3
    restart: always
    command: --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --reactor-backend=epoll
    ports:
      - "9042:9042" # CQL Port 